[WIP] Mockup speed enhancement
oursky/mockuphone.com pull request #123
Opened 2024-08-28 09:31 UTC by YayunHuang

2024-08-28 09:33 UTC, YayunHuang commented
@pkong-ds I'm still removing some scripts that are no longer used, but I think you can see if there are any big issues with this update first

2024-08-28 12:20 UTC, pkong-ds requested changes
Thanks, seems many comments. Can huddle if any misunderstanding

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/mockup_worker.js
> +      from js import locationKey, deviceInfo, deviceId, orientationIndexQueue
Can you estimate how much work if we typed the orientation instead of index?

I expect sth like

```
type Orientation = "portrait" | "landscape" | "left" ... "front" ...
```

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/mockup_worker.js
> +      print("start mockup", origin_image_path)
BTW, should this be a `main()` or `run()` function in a python file?

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +function runWorker(worker, imageUpload, orientationIndex, mode) {
Can the API still be `runPreviewWorker` and `runWorker` as 2 function?

That way the logic is contained inside each function, and no need to `if (preview) else (generate)`

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +function runWorker(worker, imageUpload, orientationIndex, mode) {
Same logic - can we also refactor as functions like `onPreviewError`, `onPreviewSuccess`?

Even better - different files for different complex logic

I planned to separate this holy 1000-line file into multiple files yesterday, but realized 
- need to move upload.js into src/pages first ; which means
- need to change all CDN into package :sadfrog:

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +  }
Sorry did not read in very detail - are we going to reuse the `portrait` orientation preview in generating mockup?

If so, should we store the `generatedMockups` by `orientation` here? (hence need the orientation typing mentioned above)


```
imageUpload {
  generatedMockups {
     "front": ...,
     "portrait": ...,
  }
}
```

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +    ).length;
`this.orientationsCount` or `this.numOrientation` or `this.numOfOrientation`?

But I prefer this to be 

```ts
this.orientations: Orientation[]
e.g. ['front', 'landscape', 'right']
```

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +  }
😱 I thought we agreed not to terminate and restart workers here? Otherwise the python modules will need to load again?

But I agree it's a lot of work to handle interrupt signal, a quick peek led me to this - https://github.com/pyodide/pyodide/issues/676#issuecomment-663863001

Let me know whether you plan to keep `terminate -> restart` worker pattern, or you wanna handle interrupt signal

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +      if (viewModel.isGeneratingMockup) {
Can we do an early return here?

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +    },
Can extract this as 2 functions?

1. call `onNewGeneratedMockup`
2. in `onNewGeneratedMockup`, call `navigateToDownloadPAge`

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +        const results = e.data["results"];
can use [destructure](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) syntax sugar here

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +        for (let i = 0; i < imageUploads.length; i += 1) {
Can add below line, cleaner

```
const imageMockups = imageUploads[i].generatedMockups
// use imageMockups below
```

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +      ),
IIUC, this reaction is 
1.  observing `every image's list of generated mockups`
  - that is, both add/remove image would trigger this
  - adding a new mockup in `imgZ` will re-construct everything for `imgA, B, C ....`
2. on trigger, apply side effects
   1.  loop through all images
   2. (re)construct all generated mockups for every image
   3. set localforage['pictureArray']

Is that what we want? Do you think we can simplify this?

Otherwise, at least add some comments/refactor as bite-size readble functions?

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +          }
Why terminate function if any image mockups do not have enough generated mockups?

2024-08-28 12:20 UTC, pkong-ds commented on public/scripts/upload.js
> +            );
Again, split functions here

2024-08-28 12:20 UTC, pkong-ds commented on mockup_package/mockup/image.py
Can you also help rename the files? `image.py` did not help me understand any context at all :sadfrog:

2024-08-28 12:25 UTC, pkong-ds commented on public/scripts/upload.js
> +  }
Or maybe this? https://github.com/SpectralSequences/pyodide_interrupts/

2024-08-29 02:51 UTC, YayunHuang commented on public/scripts/mockup_worker.js
> +      from js import locationKey, deviceInfo, deviceId, orientationIndexQueue
ok, let me add `Orientation` in `Device` model, I think 1~2pts~

2024-08-29 02:55 UTC, YayunHuang commented on public/scripts/upload.js
> +function runWorker(worker, imageUpload, orientationIndex, mode) {
@pkong-ds yes, I think it's better if we can do this after changing all CDN into package, and event typescript

2024-08-29 02:59 UTC, YayunHuang commented on public/scripts/upload.js
> +  }
@pkong-ds we can, and even better, I think we can generate previews in all orientations and we only need to compress them when the user clicks the generate button, just make sure the preview orientation is generated first (mostly portrait).

can implement it after https://github.com/oursky/mockuphone.com/pull/123#discussion_r1734496707

2024-08-29 03:03 UTC, YayunHuang commented on public/scripts/upload.js
> +          }
@pkong-ds we should only zip the mockups when all mockups are generated, don't have enough generated mockups means generation haven't done yet

2024-08-29 04:40 UTC, YayunHuang commented on public/scripts/mockup_worker.js
> +      from js import locationKey, deviceInfo, deviceId, orientationIndexQueue
please see see if this matches your expectations: https://github.com/oursky/mockuphone.com/pull/123/commits/e21d9738f434302e55a009e5af9d28e13ae662a9

2024-08-29 05:53 UTC, pkong-ds commented on public/scripts/upload.js
> +function runWorker(worker, imageUpload, orientationIndex, mode) {
As per offline discussion, let's do the refactoring while `upload.js` is moved

2024-08-29 05:54 UTC, pkong-ds commented on public/scripts/upload.js
> +  }
as per offline discussion, onImageUpload -> generate all orientations is good idea. But let's implement it later as a new feature

2024-08-29 05:54 UTC, pkong-ds commented on public/scripts/upload.js
> +  }
@YayunHuang oh we missed this, wanna talk?

2024-08-29 05:56 UTC, pkong-ds commented on public/scripts/upload.js
> +      ),
As per offline discussion, define new observable `isAllMockupGenerationFinished`, then observe this.

BTW, @YayunHuang I think you need to handle some `imageUpload` failed/errored and will not have any `generatedMockup`

2024-08-29 05:56 UTC, pkong-ds commented on public/scripts/upload.js
> +          }
Resolved if we observe `isAllMockupGenerationFinished`

2024-08-29 05:58 UTC, YayunHuang commented on public/scripts/upload.js
> +  }
@pkong-ds let's talk after standup

2024-08-29 08:21 UTC, YayunHuang commented on public/scripts/mockup_worker.js
> +      print("start mockup", origin_image_path)
updated

2024-08-29 08:26 UTC, YayunHuang commented on public/scripts/upload.js
> +  }
@pkong-ds to support partial success, updated `ImageUpload.generatedMockups` to:
```
{
    [orientationA]: {
        status: "success" | "failed"
        image: [{image name}-{orientationB}]
        results: results | null
    },
    [orientationB]: {
        status: "success" | "failed"
        image: [{image name}-{orientationB}]
        results: results | null
    },
    ...
}
```

2024-08-29 08:28 UTC, YayunHuang commented on public/scripts/upload.js
> +  }
you can add `if (orientation_name == "landscape"): raise Exception("test error")` for testing :zany_face:

2024-08-29 08:29 UTC, YayunHuang commented on public/scripts/upload.js
> +  }
open another issue: https://linear.app/oursky/issue/MUP-181/handle-interrupt-signal-instead-of-restart-worker

2024-08-29 08:42 UTC, YayunHuang commented on mockup_package/mockup/image.py
renamed to `image_mockup.py`, but I think maybe can to create a class `MockupGenerator` and put those function to the class? then we call `MockupGenerator.mockup()` to generate, what do you think?

2024-08-29 08:51 UTC, pkong-ds commented on mockup_package/mockup/image.py
Great idea! Let's go 🚀

2024-08-29 09:49 UTC, YayunHuang commented
@pkong-ds all updated

2024-08-29 19:32 UTC, pkong-ds commented
Thanks for addressing all the comments 👍 I pushed 2 commits to fix some minor stuff.

But I observe a bug (or expected behavior?) when testing this branch locally - if I upload more than 5 files, some orientations are lost. 

I can reproduce this very consistently. Can you help check check? 🙏 

## 6 images uploaded, only 8 files output


https://github.com/user-attachments/assets/a5469ad0-1fa2-4fb4-9683-c2f62b27ae78

2024-08-30 03:17 UTC, YayunHuang commented
@pkong-ds Fixed! I found that's because we add event listener in `runPreviewWorker` and `runWoker` but didn't remove them so some worker have multiple event listener so some mockups were replaced with incorrect images, fix by add `{once: true}` in `addEventListener`

2024-08-30 06:16 UTC, pkong-ds approved these changes
@YayunHuang Thanks a lot for your work🙏 🙏 LGTM

2024-08-30 06:16 UTC, merged