Fix missing image when share to facebook
oursky/mockuphone.com pull request #77
Opened 2024-08-12 06:49 UTC by YayunHuang

Ref: MUP-121

<img width="500" alt="Screenshot 2024-08-12 at 2 49 05 PM" src="https://github.com/user-attachments/assets/55efa918-9e90-4b46-a9be-5ee89d02c9a1">

2024-08-12 08:02 UTC, pkong-ds approved these changes

2024-08-12 08:06 UTC, pkong-ds requested changes

2024-08-12 08:06 UTC, pkong-ds commented on src/layouts/BaseLayout.astro
> +  "https://github.com/oursky/mockuphone.com/blob/main/public/Images/mockuphone-logo.png?raw=true";
Sor, on second thought - are we sure we want to rely on below?

1. `mockuphone.com` repo being public 
2. use github as image hosting provider

Maybe a better approach would be to use `https://mockuphone.com/Images/mockuphone-logo.png`?

2024-08-12 08:11 UTC, pkong-ds commented on src/layouts/BaseLayout.astro
> +  "https://github.com/oursky/mockuphone.com/blob/main/public/Images/mockuphone-logo.png?raw=true";
Even more robust - make sth like below?

```
# .env.production
BASE_URL = `https://mockuphone.com`
# .env.staging
BASE_URL = `https://staging.mockuphone.com`
```

2024-08-13 10:24 UTC, pkong-ds approved these changes

2024-08-13 10:24 UTC, YayunHuang commented
@pkong-ds updated image, u can run `ngrok http 3000` and set the url as `PUBLIC_BASE_URL` in `.env.local` for test

2024-08-13 10:24 UTC, merged